export const countrySeoPages = [
  { slug: "india", country: "India", region: "Asia" },
  { slug: "united-states", country: "United States", region: "North America" },
  { slug: "united-kingdom", country: "United Kingdom", region: "Europe" },
  { slug: "canada", country: "Canada", region: "North America" },
  { slug: "australia", country: "Australia", region: "Oceania" },
  { slug: "united-arab-emirates", country: "United Arab Emirates", region: "Middle East" },
  { slug: "singapore", country: "Singapore", region: "Asia" },
  { slug: "saudi-arabia", country: "Saudi Arabia", region: "Middle East" },
  { slug: "south-africa", country: "South Africa", region: "Africa" },
  { slug: "pakistan", country: "Pakistan", region: "Asia" },
  { slug: "bangladesh", country: "Bangladesh", region: "Asia" },
  { slug: "philippines", country: "Philippines", region: "Asia" },
  { slug: "malaysia", country: "Malaysia", region: "Asia" },
  { slug: "indonesia", country: "Indonesia", region: "Asia" },
  { slug: "japan", country: "Japan", region: "Asia" },
  { slug: "germany", country: "Germany", region: "Europe" },
  { slug: "france", country: "France", region: "Europe" },
  { slug: "spain", country: "Spain", region: "Europe" },
  { slug: "italy", country: "Italy", region: "Europe" },
  { slug: "mexico", country: "Mexico", region: "North America" },
  { slug: "brazil", country: "Brazil", region: "South America" },
  { slug: "argentina", country: "Argentina", region: "South America" },
  { slug: "colombia", country: "Colombia", region: "South America" },
  { slug: "chile", country: "Chile", region: "South America" },
  { slug: "peru", country: "Peru", region: "South America" },
  { slug: "ireland", country: "Ireland", region: "Europe" },
  { slug: "netherlands", country: "Netherlands", region: "Europe" },
  { slug: "belgium", country: "Belgium", region: "Europe" },
  { slug: "switzerland", country: "Switzerland", region: "Europe" },
  { slug: "austria", country: "Austria", region: "Europe" },
  { slug: "portugal", country: "Portugal", region: "Europe" },
  { slug: "sweden", country: "Sweden", region: "Europe" },
  { slug: "norway", country: "Norway", region: "Europe" },
  { slug: "denmark", country: "Denmark", region: "Europe" },
  { slug: "finland", country: "Finland", region: "Europe" },
  { slug: "poland", country: "Poland", region: "Europe" },
  { slug: "czech-republic", country: "Czech Republic", region: "Europe" },
  { slug: "romania", country: "Romania", region: "Europe" },
  { slug: "greece", country: "Greece", region: "Europe" },
  { slug: "hungary", country: "Hungary", region: "Europe" },
  { slug: "ukraine", country: "Ukraine", region: "Europe" },
  { slug: "turkey", country: "Turkey", region: "Europe / Asia" },
  { slug: "russia", country: "Russia", region: "Europe / Asia" },
  { slug: "qatar", country: "Qatar", region: "Middle East" },
  { slug: "kuwait", country: "Kuwait", region: "Middle East" },
  { slug: "oman", country: "Oman", region: "Middle East" },
  { slug: "bahrain", country: "Bahrain", region: "Middle East" },
  { slug: "israel", country: "Israel", region: "Middle East" },
  { slug: "jordan", country: "Jordan", region: "Middle East" },
  { slug: "egypt", country: "Egypt", region: "Africa / Middle East" },
  { slug: "nigeria", country: "Nigeria", region: "Africa" },
  { slug: "kenya", country: "Kenya", region: "Africa" },
  { slug: "ghana", country: "Ghana", region: "Africa" },
  { slug: "morocco", country: "Morocco", region: "Africa" },
  { slug: "ethiopia", country: "Ethiopia", region: "Africa" },
  { slug: "uganda", country: "Uganda", region: "Africa" },
  { slug: "tanzania", country: "Tanzania", region: "Africa" },
  { slug: "sri-lanka", country: "Sri Lanka", region: "Asia" },
  { slug: "nepal", country: "Nepal", region: "Asia" },
  { slug: "bhutan", country: "Bhutan", region: "Asia" },
  { slug: "maldives", country: "Maldives", region: "Asia" },
  { slug: "china", country: "China", region: "Asia" },
  { slug: "south-korea", country: "South Korea", region: "Asia" },
  { slug: "thailand", country: "Thailand", region: "Asia" },
  { slug: "vietnam", country: "Vietnam", region: "Asia" },
  { slug: "cambodia", country: "Cambodia", region: "Asia" },
  { slug: "laos", country: "Laos", region: "Asia" },
  { slug: "myanmar", country: "Myanmar", region: "Asia" },
  { slug: "hong-kong", country: "Hong Kong", region: "Asia" },
  { slug: "taiwan", country: "Taiwan", region: "Asia" },
  { slug: "new-zealand", country: "New Zealand", region: "Oceania" },
  { slug: "fiji", country: "Fiji", region: "Oceania" },
] as const;

export type CountrySeoPage = (typeof countrySeoPages)[number];

export function getCountrySeoPage(slug: string) {
  return countrySeoPages.find((item) => item.slug === slug);
}
